### ISSUE TITLE
Has files lose  

### ISSUE THREAD

**Issue by GilbertTam** [previtus/intership_project#3]
Dear,
i meet a problem when i run your code:
python run_fast_sketch.py -horizontal_splits 2 -atthorizontal_splits 1 -name "_ExampleRunNameHere"
    **import yad2k, eval_yolo, eval_yolo_direct_images
ModuleNotFoundError: No module named 'eval_yolo'**

can you provide me eval_yolo_direct_images,and eval_yolo py file?
i am not sure why i miss these file , i download https://github.com/allanzelener/YAD2K yolov2 and can inference.

**Comment by WeberChen** [comment]
Excuse me, I have the same problem. Could you tell me how to overcome this issue? Thanks a lot.

**Comment by previtus** [comment]
Hi Weber Chen,
It's been some time since running this code, so apologies if this wont be super precise.

However, I think that this occurs in the file "video_parser_v1/yolo_handler.py" when importing YOLO code from the https://github.com/allanzelener/YAD2K repository.
You might need to change the folder paths on the line 20 `yolo_paths = [...]` ([here](https://github.com/previtus/AttentionPipeline/blob/70e37142e79996e62c51c85de996127e38606efa/video_parser_v1/yolo_handler.py#L20)) to get the import for **yad2k** running.

And then place the files from "video_parser_v1/__to-be-put-with-YAD2K/" into that folder too (to get the imports for **eval_yolo**, **eval_yolo_direct_images** running).

_PS: Also, if I recall correctly, the "video_parser_v2" version which uses thtrieu/darkflow worked better on server with longer continued running..._

**Comment by WeberChen** [comment]
Thanks for your kindly help. This project is workable! By the way, I still run it with v1.
Thank you again.
