### ISSUE TITLE
Can we utilise this for custom training ?

### ISSUE THREAD

**Issue by zohaibjan** [previtus/intership_project#5]
Hi is there a way to utilize this on custom classes ?.

**Comment by previtus** [comment]
Hello,
We are just using a pre-trained YOLO model from the repository of https://github.com/thtrieu/darkflow, so it would be possible to follow their description on how to train your own model and use that one instead of the official one.
Plus you might need to make few other small adjustments in our code too - not to filter the class that you are newly detecting out - that would be likely [here](https://github.com/previtus/AttentionPipeline/blob/master/video_parser_v2/Evaluation.py#L222).

**Comment by zohaibjan** [comment]
Hi,

Thank you for replying appreciate the response. I will give it a go.

Regards
